### ISSUE TITLE
Sending multiple events of the same tx and claim

### ISSUE THREAD

**Issue by filipnyquist** [cryptodevorg/logstash-input-cortesexplorer#2]
Right now the logstash plugin is sending multiple events for all transactions and claims, this means that the checking function needs some improvment!

**Comment by wallermadev** [comment]
Good job reporting Therese fillerino.

**Comment by filipnyquist** [comment]
Tried to fix it with commit 7c8ae3cc202c5f274278fb148cb616d228d3e47a

**Comment by filipnyquist** [comment]
The error does only happen with transactions, any only if there are more than one transaction in a block.

**Comment by wallermadev** [comment]
We have updated the functionality of the importer so `document_id` is set to have a path of `txid` this acts a a way of having a unique identifier any additional calls using the same will update the existing record.
